name = "todo-preview-prod"
main = "src/index.js"
account_id = "b49212858a35492d031028fd98a0bb7d"
compatibility_date = "2025-06-08"

[[kv_namespaces]]
binding = "TODOS"
id = "eb00ad315474437581c000dc9aef4a6f"

[env.dev]
name = "todo-preview-dev"


[[env.dev.kv_namespaces]]
binding = "TODOS"
id = "b532f51b4d784eed84a644a55efa13c1"
